//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileTrackingWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Details
    {
        public int Id { get; set; }
        public string Role { get; set; }
        public Nullable<int> SalaryMin { get; set; }
        public Nullable<int> SalaryMax { get; set; }
        public string Location { get; set; }
        public string Skills { get; set; }
    }
}
